version: '3.8'

services:
  lefrog-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./static-files:/app/public/static-files:ro
